[package]
name = "winapi-app-windows"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
once_cell = "1.4.1"
winapi = { version = "0.3", features = ["libloaderapi", "winuser"] }
