[package]
name = "dlg_two"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"
build = "src/build.rs"

[target.'cfg(windows)'.dependencies]
minimal-windows-gui = "*"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.3.3"
